drop table if exists users, task, comment cascade;

CREATE TABLE IF NOT EXISTS users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email               VARCHAR(255)            NOT NULL,
    password        VARCHAR(500)            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    constraint uk_user unique (email)
);

CREATE TABLE IF NOT EXISTS task
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name               VARCHAR(255)            NOT NULL,
    description        VARCHAR(500),
    executor_id          BIGINT,
    author_id          BIGINT                  NOT NULL,
    status             VARCHAR(30)             NOT NULL,
    CONSTRAINT pk_task PRIMARY KEY (id),
    CONSTRAINT fk_task_user FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_exec FOREIGN KEY (executor_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comment
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    author_id        BIGINT                      NOT NULL,
    task_id       BIGINT                      NOT NULL,
    text             VARCHAR(600),
    publication_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id),
    CONSTRAINT fk_comment_buyer FOREIGN KEY (author_id) REFERENCES users (id) on update cascade on delete cascade,
    CONSTRAINT fk_comment_task FOREIGN KEY (task_id) REFERENCES task (id) on update cascade on delete cascade
);